### ISSUE TITLE
 NestFactory.create() returns a promise

### ISSUE THREAD

**Issue by jaufgang** [caiorcferreira/nest-js-firebase#1]
I noticed that you have 

```js
const app = NestFactory.create(ApplicationModule, server);
app.init();
```

in `server.ts`, but `NestFactory.create()` returns a promise.   I think it should be 

```js
const app = NestFactory.create(ApplicationModule, server)
    .then(app=>app.init())
```

Thank you for your write-up and this repo.  I am working to set up Nest with Firebase and all of this information is a big help.

**Comment by caiorcferreira** [comment]
Hello @jaufgang, thanks for the words. The issue was corrected and if you find more problems or if you have suggestions, please feel free to post them!
